name: Build SPFx SPPKG

on:
  workflow_dispatch:        # run manually from Actions tab
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If your SPFx project is in a subfolder, set working-directory on steps below, e.g.:
      #   working-directory: ./sharepoint-global-css
      # Otherwise leave as-is.

      - name: Use Node 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install build prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 g++ make
          npm config set python python3

      - name: Install dependencies
        run: npm ci || npm install

      - name: Bundle (production)
        run: npx gulp bundle --ship

      - name: Package solution
        run: npx gulp package-solution --ship

      - name: Upload .sppkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: sppkg
          path: sharepoint/solution/*.sppkg
